// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ5F3owOfvqVoXdt6OsQ6B1qk5gx3XJgw',
    appId: '1:1072276240951:web:1d44eec262ef50b8879db2',
    messagingSenderId: '1072276240951',
    projectId: 'sales-task-tracker-001',
    authDomain: 'sales-task-tracker-001.firebaseapp.com',
    storageBucket: 'sales-task-tracker-001.firebasestorage.app',
    measurementId: 'G-03EJPM6F6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK9JUMUWeJpG_O9W-SzY_Vq8bRaFQ5mzA',
    appId: '1:1072276240951:android:e602209952dc424a879db2',
    messagingSenderId: '1072276240951',
    projectId: 'sales-task-tracker-001',
    storageBucket: 'sales-task-tracker-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCElnlxIU4k1o0il3hLMliQKYZkLTn4n94',
    appId: '1:1072276240951:ios:a3d64ee330848e1d879db2',
    messagingSenderId: '1072276240951',
    projectId: 'sales-task-tracker-001',
    storageBucket: 'sales-task-tracker-001.firebasestorage.app',
    iosBundleId: 'com.example.salesTaskTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCElnlxIU4k1o0il3hLMliQKYZkLTn4n94',
    appId: '1:1072276240951:ios:a3d64ee330848e1d879db2',
    messagingSenderId: '1072276240951',
    projectId: 'sales-task-tracker-001',
    storageBucket: 'sales-task-tracker-001.firebasestorage.app',
    iosBundleId: 'com.example.salesTaskTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ5F3owOfvqVoXdt6OsQ6B1qk5gx3XJgw',
    appId: '1:1072276240951:web:f537cc4c925198d9879db2',
    messagingSenderId: '1072276240951',
    projectId: 'sales-task-tracker-001',
    authDomain: 'sales-task-tracker-001.firebaseapp.com',
    storageBucket: 'sales-task-tracker-001.firebasestorage.app',
    measurementId: 'G-60YTZ96LEN',
  );
}
